var keyMirror = require('keymirror');

module.exports = {
    //Registration
    INVALID_USERNAME
    INVALID_PASSWORD
    INVALID_EMAIL_PHONE
    INVALID_FIRST_NAME
    INVALID_LAST_NAME
    TRY_AGAIN_ERR
    EMPTY_LIST
    SIGNUP_NULL
    USER_NULL
    USER_EMAIL_NULL
    INVALID_COUNTRY_CODE
    INVALID_USER_TYPE
    INVALID_PHONE_NUMBER
    INVALID_OR_MISSING_ARGS
    USERS_EXITS
    USER_EXITS_EMAIL_NOT_VERIED
    USER_EXITS_EMAIL_NOT_VERFIED
    USER_EXITS_PHONE_NOT_VERFIED
    SIGNUP_FAILED
    SIGNUP_SUCCESS_MAIL_FAILED
    SIGNUP_SUCCESS_MAIL_FAILED

    //Login
    LOGIN_NULL
    INVALID_USERNAME_OR_PASSOWORD

    //Verification
    INVALID_VERIFICATION_CODE
    PHONE_VERIFICATION_FAILED
    PASSWORD_RESET_VERIFICATION_FAILED
    INVALID_EMAIL
    UNKNOWN_USER
    ALREADY_VERIFIED

    //Token
    INVALID_SER_CONTENT
    INVALID_TOKEN
    ACCESS_DENIED
    
    //Profile Pic Update
    INVALID_FILE_FORMAT
    PROFILE_PIC_UPDATE_FAILED
    NO_FILE_WAS_SENT

    //Login
    INVALID_DEVICE_SOURCE
    INVALID_USER_AGENT


    //From Common Error Codes:
    AUTHORIZATION_MISSING
    ILLEGAL_ARGUMENTS


   // Localization Update

    LOCALIZATION_UPDATE_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Profile Update

    PROFIILE_UPDATE_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR
    USERNAME_EXITS


    //Home Location Delete

    HOME_LOCATION_DELETE_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Office Information Delete

    OFFICE_INFO_DELETE_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Phone Delete Failed

    PHONE_DELETE_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Home Location Add

    HOME_LOCATION_ADD_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Office Information Add

    OFFICE_INFO_ADD_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Phone Number Add

    PHONE_NUMBER_ADD_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    Update Password
    INVALID_OLD_PASSWORD
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR
    PASSWORD_UPDATE_FAILED


    //Event
    NO_EVENT_EXITS
    NO_EVENT_ADMIN
    EVENT_STATUS_FAILED
    EVENT_DEL_FAILED
    EVENT_PARTICIPANT_ADD_FAILED
    EVENT_AGENDA_ADD_FAILED
    EVENT_AGENDA_UPDATE_FAILED
    EVENT_AGENDA_DELETE_FAILED
    EVENT_CREATE_FAILED


    //Bundle
    INVALID_BUNDLE_NAME
    ILLEGAL_ARGUMENTS
    UNKNOWN_USER
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR
    BUNDLE_NAME_EXITS
    BUNDLE_DO_NOT_EXITS
    BUNDLE_UPDATE_FAILED
    BUNDLE_ADD_FAILED
    EMPTY_LIST
    CONNECT_REQUEST_ALREADY_PRESENT
    CONNECTION_REQ_UPD_FAILED
    INVALID_TO_USER
    SAME_TO_AND_FROM_USERS
    ALREADY_EXITS_IN_BUNDLE
    TO_FROM_BUNDLE_ARE_SAME



    //Privacy Update
    PRIVACY_UPDATE_FAILED
    UNKNOWN_USER
    ILLEGAL_ARGUMENTS
    INAVLID_TOKEN
    ACCESS_DENIED
    TRY_AGAIN_ERR

    //Notification 
    UNKNOWN_NOTIFICATION
    NOTIFICATION_DO_NOT_EXITS
    NOTIFICATION_MARK_READ_FAILED
    NOTIFICATION_MARK_DELIVER_FAILED
    NOTIFICATION_DELETE_FAILED


    //Session
    PRESENCE_FAILED_TO_ADD
    INVALID_OR_MISSING_CONN_ID

    //Third Party Account
    THIRD_PARTY_ACCOUNT_ADD_FAILED
    THIRD_PARTY_ACCOUNT_DELETE_FAILED
    THIRD_PARTY_ACCOUNT_GET_FAILED
    THIRD_PARTY_ACCOUNT_AUTH_UPDATE_FAILED
}
